Glyphack/pytse-client

- pytse_client/ticker.py
Resolves: https://github.com/Glyphack/pytse-client/issues/2
> fix problem with dataframe become none

- pyproject.toml
> Change license to GPLv3

- pytse_client/download.py
<p dir="rtl"> 
بهبود سرعت دانلود دیتاها
</p>
> Improve download performance

- pytse_client/ticker.py
> Fix bug when gpe is empty

- pytse_client/download.py
- pytse_client/translations.py
> Add yesterday price

- README.md
- pytse_client/ticker/api_extractors.py
- pytse_client/ticker/ticker.py
- tests/test_ticker/ticker_e2e.py
> Add buy orders sell orders

- pytse_client/download.py
- pytse_client/ticker/ticker.py
افزودن تعدیل عملکردی به کلاس تیکر
نحوه استفاده:
ticker = tse.Ticker(symbol="بركت", adjust=True)
@TODO
افزودن تعدیل  عملکردی به کلاس دانلود
@TODO
ذخیره داده های تعدیل عملکردی جهت کاهش زمان محاسبات
> Adjust historical price data

- README.md
- pyproject.toml
- pytse_client/examples/ticker.py
- pytse_client/ticker/api_extractors.py
- pytse_client/ticker/ticker.py
- tests/test_ticker/ticker_e2e.py
> Feature add coorporate individual realtime info

- README.md
- pytse_client/examples/ticker.py
- pytse_client/ticker/ticker.py
- pytse_client/tse_settings.py
add feature #108 
گرفتن ناو صندوق‌ها #41 
دریافت NAV ابطال صندوق و زمان آن لحظه ای
> fetch NAV value

- pytse_client/download.py
> fix download price data of tickers with numerical symbol name

- README.md
- pytse_client/examples/ticker.py
- pytse_client/ticker/ticker.py
- tests/test_ticker/ticker_e2e.py
> get ticker full title

- pytse_client/scraper/symbol_scraper.py
> remove unnecessary if statement

- README.md
- pyproject.toml
- pytse_client/examples/ticker.py
- pytse_client/ticker/ticker.py
- pytse_client/tse_settings.py
- tests/test_ticker/ticker_e2e.py
#52 
ریز معاملات روز جاری
هنوز کار داره به نظر مواردی مانند دریافت همزمان باید اضافه شود.
گاهی هم جدول خالی بر می گرداند نمیدونم آیپی را بن می کند یا اینکه برخی سرورها دیتا زیر معاملات را ندارند.
> get trade details

- README.md
نحوه رفع خطای
asyncio.run() cannot be called from a running event loop
> Add docs for resolving get_shareholders_history issue

- pytse_client/download.py
> fix pandas deprecated error

- pytse_client/data/generate_indices_name.py
- pytse_client/ticker_statisticals/generate_document.py
- pytse_client/utils/symbols.py
> fix unicode decode error

- pytse_client/ticker/api_extractors.py
- pytse_client/ticker/dto.py
- pytse_client/ticker/ticker.py
- pytse_client/tse_settings.py
- tests/test_ticker/test_ticker.py
> get title from instrument info api

- pytse_client/ticker/api_extractors.py
#213 رفع مشکل عدم نمایش درست اطلاعات قیمت و تعداد سفارش ۵ مظنه برتر در بخش عرضه
> fix supply price and count

- pytse_client/proxy/tsetmc.py
- pytse_client/utils/scrape.py
کامل کردن اطلاعات سهامداران لحظه‌ای #211
> fix share holder id

- pytse_client/utils/__init__.py
اینجا فراموش کردم تابع را تغییر نام بدم توی تست خطا داد بهم
> fix function name get_html_table_header_and_rows_and_ids in utils

- README.md
- pytse_client/ticker_statisticals/utils.py
#260 با استفاده از این اطلاعات جدید میتوان نمادها را بهتر فیلتر کرد.
دو کلید مهم اضافه شده 
یکی کلید flow است:
0 : عمومي - مشترک بين بورس و فرابورس
1 : بورس
2 : فرابورس
3 : مشتقه
4 : پايه فرابورس
5 : پايه فرابورس (منتشر نمي شود)
6 : بورس انرژي
7 : بورس کالا
و دیگری کلید yval نوع اوراق می باشد.
67 | شاخص | شاخص قيمت
68 | شاخص | شاخص
200 | اوراق مشارکت | اوراق مشارکت انرژي
208 | اوراق مشاركت | اوراق صكوك
300 | سهام عادي | سهام
305 | صندوق سرمايه گذاري | صندوق سرمايه گذاري در سهام بورس
309 | تست پايه | تست پايه
321 | اختيار فولاد هرمزگان |  
322 | اختيار خ اخزا ( اسناد خزانه داري اسلامي ) |  
323 | اختيارف اخزا ( اسناد خزانه داري اسلامي ) |  
400 | حق تقدم | حق تقدم سهم
 ---
69 | شاخص | شاخص فرابورس
70 | اوراق مشاركت | صکوک اختصاصي
303 | سهام عادي | اتيسي
305 | صندوق سرمايه گذاري | صندوق …
> define not valid keys of market watch

- pytse_client/stats.py
اینکه نمیشه تست ها را اجرا کرد خیلی اذیت کننده شده است. حتی روی لوکال هم امکانش نیست و آیپی بلاک میشه و کلی خطا میدهد. باید برای یونیت تست یه فکری کرد. الان متوجه شدم تغییرات اخیرم خطا داشته لطفا قبل از ریلیز این فیکس را مرج کنید.
> fix KeyError: 'NOT_VALID_KEY'
